use_frameworks!

target 'ByvManager_Example' do
  pod 'ByvManager', :path => '../'
  pod 'Firebase'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Google/Analytics'

  target 'ByvManager_Tests' do
    inherit! :search_paths

    
  end
end
